server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      name: eureka-server
      uri: http://localhost:8762

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

endpoints:
 shutdown:
  enabled: true
