server:
  port: 8770

spring:
  application:
    name: info-server
  cloud:
    config:
      name: info-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
